input:
  port:
    ### 监听端口设置
    udp: 9897
    tcp: 9898
    tls: 9899
filter:
  # 可选值为: RFC_5424, RFC_3164, UNKNOWN
  protocol: RFC_5424
### 导出设置
### 用哪个就写哪个, 不用的就可以不写
output:
  stdout:
#  file:
#    path: "/Users/milu/data/tmp/syslog/temp.txt"
#  kafka:
#    bootstrapServers: "localhost:9092"
#    zkAddress: "localhost:2181/kafka"
#    topics: "milu_test"
#    producerSettings: {"max.request.size":"20971520","compression.type":"lz4","request.timeout.ms":"86400000","retries":"1000000","max.in.flight.requests.per.connection":"1"}
